
labelRegion={
"SignalRegionPhase1"  : "Signal Region",
"SideBandPhase1"      : "SideBand",
"ZRegionPhase1"       : "Z Region",
"ZRegionPhase1"       : "Z Region",
"TwoJetsTwoMuPhase1"  : "2 Jets and 2 opposite Muons",
}




labelVariable={
"LeadMuonPhase1_pt"       : "p_{T}(#mulead)",
"LeadMuonPhase1_eta"      : "#eta(#mu lead)",
"SubMuonPhase1_pt"        : "p_{T}(#mu sublead)",
"SubMuonPhase1_eta"       : "#eta(#mu sublead)",
"QJetPhase1_0_eta"         : "#eta(leading jet)",
"QJetPhase1_1_eta"         : "#eta(subleading jet)",
"QJetPhase1_0_pt_nom"      : "p_{T}(#mu lead)",
"QJetPhase1_1_pt_nom"      : "p_{T}(#mu sublead)",
"PV_npvsPhase1"           : "number of primary vertices",
"fixedGridRhoFastjetAllPhase1"           : "energy density #rho",
"LeadingSAJet_ptPhase1"   : "p_{T}(soft leading jet)",
"NSoft10New2Phase1"       : "# soft jet p_{T}>10",
"NSoft5New2Phase1"        : "# soft jet p_{T}>5",
"NSoft2New2Phase1"        : "# soft jet p_{T}>2",
"SAHTPhase1"              : "soft Activity HT",
"SAHT5Phase1"             : "soft Activity HT p_{T}>5",
"nFootprintSAJetPhase1"   : "nFootprintSAJet",
"FootHTPhase1"            : "FootHT",
"Mqq_Phase1_log"           : "log( M(jj) )",
"Mqq_Phase1_over400_log"   : "log( M(jj)/400 )",
"mmjj_Phase1_pt"           : "p_{T}(#mu#mujj)",
"qqDeltaEtaPhase1"        : "#Delta#eta(j,j)",
"NSoft5Phase1"            : "# soft jet p_{T}>5 old version",
"ll_zstarPhase1"          : "z*",
"Higgs_Phase1_pt"          : "p_{T}(#mu#mu)",
"theta2Phase1"            : "cos(#mu#mu, subleading jet)",
"mmjj_Phase1_pz"           : "p_{Z}(#mu#mujj)",
"MaxJetAbsEtaPhase1"      : "max( |#eta(j lead)|, |#eta(j lead)| )",
"Higgs_Phase1_m"           : "M(#mu#mu)",
"SBClassifierPhase1"      : "BDT output",
"BDTAtanPhase1"           : "BDTAtanh((BDT+1)/2)",
"Higgs_Phase1_m_uncalib"   : "M(#mu#mu) uncalib",
"NSoft5NewPhase1"         : "# soft jet p_{T}>5 equivalent version",
"ll_zstarPhase1_log"      : "log(z*)",
"SBClassifierZPhase1"     : "BDT output (m=125)",
"BDTAtanZPhase1"          : "atanh((BDT+1)/2) (m=125)",
"SBClassifierNoMassPhase1": "BDT output (m=125)",
"BDTAtanNoMassPhase1"     : "atanh((BDT+1)/2) (m=125)",
"DNN18AtanPhase1"         : "atanh(DNN)",
"DNN18AtanNoMassPhase1"   : "atanh(DNN) (m=125)",
"DNNAtanPhase1"           : "atanh(DNN)",
"DNNAtanNoMassPhase1"     : "atanh(DNN) (m=125)",
"DNNZAtanPhase1"          : "atanh(DNN Z vs DY)",
"DNNwithZAtanPhase1"           : "atanh(DNN with Z peak)",
"DNNwithZAtanNoMassPhase1"     : "atanh(DNN with Z peak) (m=125)",

}
